apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: file-sending-service-a
  namespace: default
spec:
  template:
    spec:
      containers:
        - # This corresponds to
          # https://github.com/knative/eventing/tree/main/cmd/event_display/main.go
          image: alnicole0103/knative-poc:2.0
          env:
            - name: MESSAGE_TYPE
              value: A
