apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092 # note the kafka namespace
  topics:
    - knative-poc-topic
  sink:
    ref:
#      apiVersion: serving.knative.dev/v1
#      kind: Service
#      name: event-display
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      namespace: default
      name: kafka-broker