apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-a
spec:
  broker: kafka-broker
  filter:
    attributes:
      type: dev.knative.kafka.event
      kafkaheadermessagetype: a
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: file-sending-service-a
    uri: /event
