apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-b
spec:
  broker: kafka-broker
  filter:
    attributes:
      type: dev.knative.kafka.event
      kafkaheadermessagetype: b
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: file-sending-service-b
    uri: /event
